name: Amplify Backlog Deployment
on:
  push:
    branches:
      - backlog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Call Amplify Webhook
        run: curl -X POST -d {} "https://webhooks.amplify.us-east-1.amazonaws.com/prod/webhooks?id=${{ secrets.AWS_ID_BL }}&token=${{ secrets.AWS_TOKEN_BL }}&operation=startbuild" -H "Content-Type:application/json"
